### ISSUE TITLE
Todo의 repeatDay 표시, 저장 문제

### ISSUE THREAD

**Issue by Delf-Lee** [team-Devist/Devist#19]
HTML태그나 Thymeleaf의 사용 방법을 더 조사해 볼 필요가 있을 것 같습니다.

- boolean[]으로 저장했을 때, false값이 저장이 안되는 현상 발견
   - '월수금'를 저장하면, 그냥 true값 세 개만 저장
- String[]으로 저장했을 때, 불러올 시 다른 값이 나타나지 않는 현상 발견
   - '월수금'을 저장하면, 글 수정시 '월수금'이외의 체크박스가 나타나지 않음
   - 체크박스 자체는 '월~금' 모두 나타나는게 정상

**Comment by Delf-Lee** [comment]
@cjh5414 

``` java
@RequestMapping(value = "/add", method = RequestMethod.GET)
public String addForm(Model model) {
    model.addAttribute("todo", new Todo());
    return "addtodo";
}
```
근본적은 고민은 
> `Todo`를 view에 넘긴 채로 `int repeatDay`를 채워서 가지고 올 수 있는가?

입니다. 

혹시 좋은 방법이 있을까요?

생각했던 방법으로는
1. `Todo`에 `boolean[]`을 추가하여 view에서 데이터를 채우고, 나중에 `int repeatDay`로 변환하기
2. DTO를 둬서 DTO에서는 `boolean[]`, Entity에서는 `int repeatDay`로 관리하기
3. (미지의 방법) thymeleaf를 이용해서 `int repeayDay`에 해당하는 정보를 가져오고 보여주기

1번 방법을 실행중이었으나 `int repeatDay`변환하는 타이밍이 애매했고, 2번 방법은 구조를 조금 많이 바꿔야할 것 같아 상의가 필요해보이고, 3번방법은 (지금까지는) 제 상상 속의 방법입니다.

혹시 도움이 될만한 적절한 정보를 가지고 있으면 알려주세요ㅎㅎ

**Comment by cjh5414** [comment]
Todo 에 repeatDay를 boolean[] 형태로 그리고 반대로 변환해주는 메소드를 추가해서 사용하고 model 에 boolean[] 형태로 넣어서 넘겨주면 어떨까요?

**Comment by Delf-Lee** [comment]
이해한게 맞다면

``` java
@RequestMapping(value = "/add", method = RequestMethod.GET)
public String addForm(Model model) {
    model.addAttribute("todo", new Todo());
    model.addAttribute("repeayDayArr", new ArrayList());
    return "addtodo";
}
```

가 되는게 맞나요?

**Comment by cjh5414** [comment]
넵
저 repeatDayArr를 Todo에 맴버변수로 관리하면 더 깔끔할 것 같지만 그럴 필요까지 있나 싶고 동기화 문제도 있을 것 같아서..

**Comment by Delf-Lee** [comment]
1번 해결방법에서 따로 repeatDayArr 떨어트린 셈이군요...

그러면 어찌됐든 그 변환 메소드를 호출해야하는(아마 서비스 레이어에서) 번거로움이 생기겠네요... 
과연 그게 좋은 코드인지는 모르겠습니다만, 현재로써는 최선인거 같네요.

추후에 DTO 생성을 고려해보거나 다른 방법이 생기면 바꾸는게 좋을 것 같네요.
일단 이슈는 열어두겠습니다.

감사합니다 😄

**Comment by Delf-Lee** [comment]
현재 반복일(repeat days)을 표시하려면 아래와 같은 과정이 필요했습니다.
(`byte`에서 `boolean[]`으로 변환하는과정)

``` java
todo.convertRepeatDayByteToBooleanArr(); // 변환
model.addAttribute("todo", todo); // model에 넣어줌
```
이렇게 단일로 보여줄 때는 상관없지만 [모든 할일 보기] 페이지에서는 다음과 같이 model에 `List`를 넘겨줍니다.

``` java
@GetMapping
public String getTodoList(Principal principal, Model model) {
    User user = userService.getUserByUserName(principal.getName());
    List<Todo> todoList = user.getTodoList();
    model.addAttribute("todo_list", todoList); // list를 넣어줌
    return "todo_list";
}
```

이 `List`내의 todo들은 `convertRepeatDayByteToBooleanArr()`과정을 거치지 않아 현재 상태의 repeatDay가 정상정으로 표시되지 않는 문제가 있습니다.

**Comment by cjh5414** [comment]
그냥 단순히 TodoList를 전부 convertRepeatDayByteToBooleanArr 해주는 함수를 추가해서 사용하면 어떨까요?

**Comment by Delf-Lee** [comment]
매번 DB에 접근할때마다 변환하는 과정은 번거롭고 안좋은 방법이라고 판단했습니다.

이에 DB에 저장하는 데이터와 view에 넘겨주는 데이터를 통일하고 다음과 같은 기능을 추가합니다.
- 반복 주기 확장
    - ex) 지금은 1주 -> n주
- 일정 기한 내, 언제든 상관 없이 n번 완료하는 할일
    - ex) 주 마다 언제든 관계없이 2회 완료
- 일정 기한 내, 정해진 요일에 완료하는 할일
    - ex) 월, 금에 완료

이를 위하여 repeatDay에 대한 정보를 `byte`가 아닌 따로 클래스로 정의합니다.
클래스의 구성과 역할은 추후에 정하겠습니다.

**Comment by Delf-Lee** [comment]
repeatDay에 대한 정보를 클래스화하고 Entity로 만들어 관리합니다.
다음과 같은 기능 및 특성은 추상클래스와 인터페이스로 공통된 기능을 뽑아내고 묶어서 구현합니다.

> * 반복 주기 확장
>   * ex) 지금은 1주 -> n주
> * 일정 기한 내, 언제든 상관 없이 n번 완료하는 할일
>   * ex) 주 마다 언제든 관계없이 2회 완료
> * 일정 기한 내, 정해진 요일에 완료하는 할일

관련된 이슈를 새로 생성합니다.

**Comment by Delf-Lee** [comment]
해당 이슈를 #64 에서 관리합니다.
