### ISSUE TITLE
UserRepository 회원 가입 테스트 코드에서 Repository를 통해서 못 가져옴.

### ISSUE THREAD

**Issue by cjh5414** [team-Devist/Devist#8]
가상 서버 돌려서 회원가입 해보면 정상작동하는데 UserRepositoryTests 는 통과 못함.
회원가입 post request 날린 후 200 뜨는데 
Repository 통해서 생성한 User 가져오려고 하면 찾을 수 없다고 함.
테스트에서 사용하는 DB와 Repository 등 설정 확인해 볼 필요.

**Comment by Delf-Lee** [comment]
contoller test에서는 DB를 변경할 수 없는 게 아닐까 싶었지만, TodoControllerTests에서 todo를 추가 가능한 것을 확인했기 때문에 그런건 아닌 것 같습니다.

mock 설정(매개변수 혹은 호출된 메소드 등)의 문제가 아닌가 추측해봅니다.
response를 확인한 결과, `signup.html`에 해당하는 내용이었고, redirection url 값도 `null`이었습니다.

다만, "무언가 문제가 있는데 왜 ok(200)를 반환하는지"는 의문입니다만...

``` java
MvcResult result = mockMvc.perform(post("/signup")
            .param("username", "user1")
            .param("password", "user1234")
            .param("name", "name1")
            .with(csrf()))
            .andExpect(status().isOk()).andReturn();

System.out.println(result.getResponse().getContentAsString()); // signup.html
System.out.println(result.getResponse().getRedirectedUrl()); // null
```
